### ISSUE TITLE
Compilation error: No such file "femmversion.sh"

### ISSUE THREAD

**Issue by Maltimore** [Reoptimize-Systems/xfemm#4]
I tried to follow the installation instructions. On Ubuntu 20.04, I did:

1. change to mfemm directory
2. Run octave
3. In octave, run `mfemm_setup()`

The error I get after a while of compiling various files:
```
femm/mfemm/../cfemm/libfemm/femmversion.cpp
/home/maltimore/repos/xfemm/mfemm/../cfemm/libfemm/femmversion.cpp:1:10: fatal error: femmversion.h: No such file or directory
    1 | #include "femmversion.h"
      |          ^~~~~~~~~~~~~~~

```

**Comment by crobarcro** [comment]
You need to first build the standalone version with CMAKE to generate femmversion.h
