### ISSUE TITLE
fmesher.m crashing

### ISSUE THREAD

**Issue by gforti84** [Reoptimize-Systems/xfemm#5]
The function fmesher is crashing matlab. I am using win8.1 64bits and matlab 2020b. To overcome this, I am using system('C:\Dados\xfemm_mingw_win64\cfemm\bin\fmesher mag_tutorial.fem');
Also, during installation, the femmversion.h.in is causing some issues. I used the earlier vesrion from sourceforge.

**Comment by gforti84** [comment]
Hello. I changed my machine and didn't try it yet.

**Comment by reos-rcrozier** [comment]
There is a new release, so I'm going to close this for now, but please feel free to request it's reopened if the issue is still present.
