### ISSUE TITLE
xfemm 8x slower on linux than femm with wine

### ISSUE THREAD

**Issue by temudschin** [REOptimize-Systems/xfemm#7]
I am really happy with xfemm, because it offers the possibility to run hundreds of jobs an a linux computer cluster. Thanks for that!

However, solving with femm under wine runs about 8 times faster than xfemm (femmcli). Did some else experience this as well?

I compiled xfemm with gcc-8.5 as Release (CMAKE_BUILD_TYPE).

**Comment by temudschin** [comment]
I played around with the compiler flags:
-O0 is slowest (as expected)
-O1 and -O2 are fastest
combining -O2 with -ftree-vectorize gives same results like -O3 and is 2times slower than -O1 or -O2.

But even the fastest flags are around 4x slower than femm under wine ....

**Comment by temudschin** [comment]
Ok, my mistake, with xfemm smart meshing is enabled, so the mesh is bigger compared to the femm version. With same meshes, xfemm is faster than femm with wine.
Is there a lua command to deactivate smart meshing? I changed the default value in the source  code now to disable smart meshing.
Thanks again for this great peace of software!

**Comment by reos-rcrozier** [comment]
In xfemm smart meshing can be specified in the input file.

**Comment by temudschin** [comment]
Ok, how?
I tried smartmesh(0), mi_smartmesh(0) and dosmartmesh(0), neither worked ......

**Comment by reos-rcrozier** [comment]
in femm unfortunately there is no equivalent as it is program wide option, not a per-problem setting. In xfemm I made it so you can set it in the input file. So there is a flag in the input file something like `smartmesh=on` (but this is from memory and I can't remember exactly). In my Matlab/Octave interface there is a way of setting it when you create the problem, but there is no equivalent lua command.

**Comment by reos-rcrozier** [comment]
p.s. please use the 1.9 release of xfemm, available as a download from Sourceforge. Don't compile from the master branch, it's broken.

**Comment by temudschin** [comment]
Ok, I checked xfemm-3 and it produces the same results than femm, so I was quite happy with this version and the smart mesh, I am fine with deactivating it in the source files. I think, xfemm-3 should support the frozen permeability thing, isn't it?

**Comment by temudschin** [comment]
Oh, and femmcli is missing, so I do not see a way to run a lua script in 1.9. Can you explain, what is broken in v3?
